# Generated by Django 4.1 on 2022-09-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=250)),
                ('price', models.FloatField()),
                ('url', models.URLField()),
                ('category', models.CharField(max_length=64)),
            ],
        ),
    ]
