# Generated by Django 4.1 on 2022-09-16 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_remove_watchlist_item_remove_watchlist_watcher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='item',
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='watcher',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='item',
            field=models.IntegerField(null=True),
        ),
    ]
