# Generated by Django 4.1 on 2022-09-24 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_listing_highest_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='highest_bid',
            new_name='highest',
        ),
    ]
