# Generated by Django 4.1 on 2022-09-24 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_rename_highest_bid_listing_highest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='highest',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
