# Generated by Django 4.1 on 2022-09-24 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_alter_listing_highest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='highest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.bid'),
        ),
    ]
