# Generated by Django 4.1 on 2022-09-24 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_alter_listing_category_alter_listing_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='highest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auctions.bid'),
        ),
    ]
