# Generated by Django 4.1 on 2022-09-25 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_alter_listing_highest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
